### PR TITLE
Add conversion and promotion rules between Jacobi and Legendre

### PR DESCRIPTION
**Pull request by putianyi889**

### CODE REVIEW

**Comment by dlfivefifty** [comment]
Can you add tests to show why these changes are needed?

**Comment by putianyi889** [comment]
These changes are not necessary. I just feel weird not to have conversion and promotion rules. They make operations between different types cleaner.

**Comment by dlfivefifty** [comment]
Yes but can you add tests?

Note you can't always promote to a different type since `Ultraspherical <: AbstractJacobi` but `Ultraspherical(λ) ≠ Jacobi(λ-/12,λ-1/2)` since the normalisation is different.

**Comment by putianyi889** [comment]
Added tests.

**Pull request closed without merging**
